blank_issues_enabled: false
contact_links:
  - name: â“ æé—® / Ask questions
    url: https://github.com/CKylinMC/PasteMe/discussions/new?category=%E9%97%AE%E7%AD%94
    about: å‘ä»–äººå¯»æ±‚å¸®åŠ©
  - name: ğŸ’¡ å¥½ç‚¹å­ / Good ideas
    url: https://github.com/CKylinMC/PasteMe/discussions/new?category=%E5%A5%BD%E7%82%B9%E5%AD%90
    about: ä¸ç¡®å®šæ˜¯å¦é€‚åˆIssueçš„æƒ³æ³•ä¸å»ºè®®
  - name: âœ¨ åˆ†äº«å†…å®¹ / Share content
    url: https://github.com/CKylinMC/PasteMe/discussions/new?category=%E5%B1%95%E7%A4%BA
    about: åˆ†äº«ä½ çš„æç¤ºè¯ç­‰å†…å®¹
  - name: â¬‡ï¸ ä¸‹è½½æœ€æ–°ç‰ˆæœ¬
    url: https://github.com/CKylinMC/PasteMe/releases/latest
    about: ç›´è¾¾æœ€æ–°ç‰ˆæœ¬çš„ä¸‹è½½åœ°å€
